apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f ./docker-kompose.yaml
    kompose.version: 1.22.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: mediawiki
  name: mediawiki
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: mediawiki
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f ./docker-kompose.yaml
        kompose.version: 1.22.0 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.service: mediawiki
    spec:
      containers:
        - image: mediawiki
          name: mediawiki
          ports:
            - containerPort: 80
          resources: {}
          volumeMounts:
            - mountPath: /var/www/html/images
              name: mediawiki-claim0
      restartPolicy: Always
      volumes:
        - name: mediawiki-claim0
          persistentVolumeClaim:
            claimName: mediawiki-claim0
status: {}
